version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: nobodykid/hello_libasyik
    machine: true
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build . -t $IMAGE_NAME:0.1.0
      - run:
          name: Archive Docker image
          command: docker save -o $IMAGE_NAME.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  save-artifacts:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/$IMAGE_NAME.tar
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - save-artifacts:
          requires:
            - build
          filters:
            branches:
              only: master